### ISSUE TITLE
sendForm error

### ISSUE THREAD

**Issue by TheBaldCool** [inxomnyaa/MagicWE#11]
What core you use? Steadfast and pmmp dont have this function

**Comment by Enrick3344** [comment]
You gotta be using the FormAPI branch of PMMP.

**Comment by thebigsmileXD** [comment]
y u no read. Duplicate of #1 #2 #3

**Comment by inxomnyaa** [comment]
*duplicate of all issues in UI driven plugins:

https://github.com/thebigsmileXD/WarpUI/issues?q=is%3Aissue+is%3Aclosed
https://github.com/thebigsmileXD/SignEditor/issues?q=is%3Aissue+is%3Aclosed
https://github.com/thebigsmileXD/UIRules/issues?q=is%3Aissue+is%3closed

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/wiki/Command:---brush#troubleshooting
