### ISSUE TITLE
[IDEA] Get Blocks IDs in the selected area

### ISSUE THREAD

**Issue by Gianluxx** [inxomnyaa/MagicWE#114]
Would be cool to get all Blocks IDs in a selected area to analyze the area

**Comment by Gianluxx** [comment]
#10

**Comment by inxomnyaa** [comment]
Milestone set to 9.0.0 as i think this can be done best in async tasks

**Comment by inxomnyaa** [comment]
Command name: `//count` as in WorldEdit https://wiki.sk89q.com/wiki/WorldEdit/Reference

**Comment by inxomnyaa** [comment]
Command added

Will be closed when `experimental/async` is merged
