### ISSUE TITLE
Error when executing command in console

### ISSUE THREAD

**Issue by MCPE-PC** [inxomnyaa/MagicWE#117]
When I run command(/pos1) in console:
`[MagicWE] Argument 1 passed to xenialdan\MagicWE2\API::getSession() must be an instance of pocketmine\Player, instance of pocketmine\command\ConsoleCommandSender given, called in phar:///home/mcpepc/vem/plugins/MagicWE2.phar/src/xenialdan/MagicWE2/commands/Pos1Command.php on line 39`
Other commands, too.

**EDIT**: I am using thebigsmileXD/MagicWE2@c0570a7

**Comment by inxomnyaa** [comment]
Intentional. A console can not use the commands.

If you want to fill/copy etc. anyways without the need of a player, you may use the api.

**Comment by Aericio** [comment]
What if I want to make selections on console? >:C

Stop this discrimination!
