### ISSUE TITLE
Add //fix

### ISSUE THREAD

**Issue by RubyTemple** [inxomnyaa/MagicWE#118]
Pls add //fix too fix the downloaded map bugs

**Comment by Aericio** [comment]
I think this should be done with another plugin, not MagicWE2.

**Comment by RubyTemple** [comment]
Aericio, I'm TheWalker on telegram, xenial Dan asking me to open this ticket

**Comment by inxomnyaa** [comment]
I will actually not implement this, i may consider to do so in the future though. For now, please use map conversion plugins
