### ISSUE TITLE
Prefix has no color

### ISSUE THREAD

**Issue by inxomnyaa** [inxomnyaa/MagicWE#122]
Though defined, the command prefix (`Loader::$prefix`) has no color in console nor player chat.
Need help!

**Comment by inxomnyaa** [comment]
Apparently PMMP has a bug that resets colors upon `TextFormat::BOLD`
Fixed by putting `TF::BOLD` before `TF::GOLD` ^^"

**Comment by inxomnyaa** [comment]
@dktapps is this intentional behaviour?
`TextFormat::BOLD . TextFormat::GOLD . "[MagicWE2]"` works,
`TextFormat::GOLD . TextFormat::BOLD . "[MagicWE2]"` doesn't

**Comment by dktapps** [comment]
sounds like a client bug to me

**Comment by inxomnyaa** [comment]
This is the console, though i am on a quite old pmmp version
