### ISSUE TITLE
[MWE2] CustomUI NOT found, can NOT use ui-based commands

### ISSUE THREAD

**Issue by teracube** [inxomnyaa/MagicWE#124]
when server start i have this message if i put or not customui on the plugin folder

2019-08-10 [19:02:44] [Server thread/NOTICE]: [MWE2] CustomUI NOT found, can NOT use ui-based commands

https://jenkins.pmmp.io/job/PocketMine-MP/1774/artifact/PocketMine-MP.phar
https://poggit.pmmp.io/r/64022/MagicWE2_dev-167.phar
https://poggit.pmmp.io/r/44509/customui_dev-31.phar

**Comment by Aericio** [comment]
CustomUI is supposed to be loaded in as a virion, you shouldn't need to download it. 
I just checked unphar'd dev-167 and the libs are in there. Not sure what's wrong.

Path: `2019-08-12-10-39-46.tar\src\xenialdan\MagicWE2\libs\xenialdan\customui`

**Comment by inxomnyaa** [comment]
If you run from source, make sure you have DEVirion and 
> if i put or not customui on the plugin folder

put it in the virion folder instead.

The poggit phar has everything needed, works as expected for me
