### ISSUE TITLE
Flip not respecting rotation variants

### ISSUE THREAD

**Issue by inxomnyaa** [inxomnyaa/MagicWE#17]
Stairs
Slabs
Torches
Logs
levers
buttons
etc

**Comment by Aericio** [comment]
+ //flip never flips correctly, too.

**Comment by inxomnyaa** [comment]
Discontinued for now - waiting for PMMP changes for rotation values

**Comment by inxomnyaa** [comment]
Outdated issue - Flagged as discontinued
