### ISSUE TITLE
Schem Problem

### ISSUE THREAD

**Issue by jrodr10** [inxomnyaa/MagicWE#28]
type /schem
nothing happens

**Comment by jrodr10** [comment]
No error, just nothing

**Comment by jrodr10** [comment]
Command is clearly registered because a description of the command comes up... but uh nothing else happens

**Comment by inxomnyaa** [comment]
Please do not spam comments, combine them into 1. Are you sure you enter //schem, not /schem?

**Comment by jrodr10** [comment]
Yeah //schem

**Comment by inxomnyaa** [comment]
//schem load works fine for me. Are your schematics that you want to load in the correct folder? `/plugins/MagicWEv2/schematics`?

**Comment by jrodr10** [comment]
I'll have test sometime today been busy

**Comment by ghost** [comment]
It's weird that I don't even have that folder.
Tried creating one, nothing changed.
