### ISSUE TITLE
Paste multi-world issue

### ISSUE THREAD

**Issue by JaapTijmes** [inxomnyaa/MagicWE#30]
Please add multiwolrd support for paste thinks in athor worlds

**Comment by inxomnyaa** [comment]
I thought that it was fixed recently, via

https://github.com/thebigsmileXD/MagicWE2/commit/843755ae7fbb0095cb92744113ecb62087b9e92e#diff-79ea243c41229ac096608a76ad005bf8R110

on that exact line. Will recheck + probaby fix ASAP
