### ISSUE TITLE
Problem with //debug - enchantments api

### ISSUE THREAD

**Issue by ghost** [inxomnyaa/MagicWE#31]
[[MagicWE] ] Argument 1 passed to pocketmine\item\Item::addEnchantment() must be an instance of pocketmine\item\enchantment\EnchantmentInstance, instance of pocketmine\item\enchantment\Enchantment given, called in F:\PocketMine 19133\plugins\MagicWE2-master\src\xenialdan\MagicWE2\commands\DebugCommand.php on line 37 

I think this is because of enchant changes in pocketmine recently.

**Comment by thebigsmileXD** [comment]
Hey @dktapps, here, just because it's christmas, a special gift for you:👉🏼👌🏽  😒  🖕🏽
After christmas: :kms:

**Comment by dktapps** [comment]
in reply to OP: don't use bleeding-edge builds ¯\\_(ツ)\_/¯

**Comment by thebigsmileXD** [comment]
Telling a plugin dev who has to use bleeding edge to be up to date asap when the release comed NOT to use bleeding edge is like telling trump to be intelligent @dktapps ;)

**Comment by dktapps** [comment]
**in reply to OP**, who is obviously not the developer.

**Comment by thebigsmileXD** [comment]
@dktapps ikd what OP is. Fixed your shrug ascii, enjoy christmas :)

**Comment by ghost** [comment]
Thanks, fixed with the latest update.

**Comment by inxomnyaa** [comment]
Thx. Forgot to close
