### ISSUE TITLE
Where and how can I get a schematic to upload? 

### ISSUE THREAD

**Issue by shavindanagapen** [inxomnyaa/MagicWE#32]

**Comment by ghost** [comment]
@thebigsmileXD Told me to check README but there's nothing about it.

**Comment by inxomnyaa** [comment]
Upload.. Uhm.. Internet?

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/wiki/Command:---brush#troubleshooting
