### ISSUE TITLE
//brush doesn't work

### ISSUE THREAD

**Issue by llronaldoll** [inxomnyaa/MagicWE#37]
//brush doesn't work

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/issues/36
https://github.com/thebigsmileXD/MagicWE2/issues/11
Thanks for doing research before opening an issue, and for so much information/debug 👍

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/wiki/Command:---brush#troubleshooting
