### ISSUE TITLE
How to use //schem - Command explaination

### ISSUE THREAD

**Issue by cbymc** [inxomnyaa/MagicWE#38]
how do i use schematics?

**Comment by IllegalerKater** [comment]
I think ist isn't implementiert yet :/

**Comment by IllegalerKater** [comment]
I think it's not implemented yet*

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/blob/master/src/xenialdan/MagicWE2/commands/SchematicCommand.php#L59

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/tree/schematics this branch might work out for you, though several fixes and features are missing.

**Comment by inxomnyaa** [comment]
Just patched the fixes and changes into the branch (schematics)

Generic usage:
//schem

Saving a clipboard (example: `//copy`-ed area) to a file:
//schem save FileName

Loading a schematic to clipboard:
//schem load FileName

Reloading previousely loaded schematics:
//schem reload

**Comment by inxomnyaa** [comment]
Added to [Wiki](https://github.com/thebigsmileXD/MagicWE2/wiki/Command:---schem)
