### ISSUE TITLE
error brush

### ISSUE THREAD

**Issue by llronaldoll** [inxomnyaa/MagicWE#39]
when I try to use the command '' // brush '' I get this error
[Server thread/ERROR]: [[MagicWE] ] Call to undefined method pocketmine\Player::sendForm()

**Comment by inxomnyaa** [comment]
For sending the same issue twice you are now blocked from my account. 
![image](https://user-images.githubusercontent.com/8733998/34657159-e2e146b2-f423-11e7-980e-47b84f2f8189.png)
Duplicate of https://github.com/thebigsmileXD/MagicWE2/issues/37
