### ISSUE TITLE
Invalid plugin.yml provided

### ISSUE THREAD

**Issue by thefuncraftmcpe** [inxomnyaa/MagicWE#44]
Hi! The plugin.yml provided is invalid when I tried converting the .zip file to .phar. Is there a way I can download the .phar version of this plugin directly? Please help! My server needs it a lot! Thanks!

**Comment by inxomnyaa** [comment]
https://poggit.pmmp.io/ci/thebigsmileXD/MagicWE2/MagicWE2

**Comment by inxomnyaa** [comment]
I do not think the yml is invalid though.
