### ISSUE TITLE
Suggestion for new commands

### ISSUE THREAD

**Issue by MrCakeSlayer** [inxomnyaa/MagicWE#45]
I noticed this world edit plugin was missing some popular commands, Not sure if you have a list of these already but felt like I could list them for you:
- //sphere
- //cylinder
- //wall
- //anchor
- //cut

These may already exist, If they do you can ignore them, This was just based off of my initial review of the plugin. :)

**Comment by ataberkw** [comment]
Yea we really need this commands.

**Comment by inxomnyaa** [comment]
Duplicate of #2 #21 and more
