### ISSUE TITLE
Update to 3.0.0-ALPHA11

### ISSUE THREAD

**Issue by brexmania123** [inxomnyaa/MagicWE#48]
Hi so i have noticed that you havent updated the plugin to 3.0.0-ALPHA11 for pocketmine yet. Can you please do that? THX

**Comment by inxomnyaa** [comment]
-11 is not merged to master in pmmp nor findable

**Comment by JackNoordhuis** [comment]
oof https://github.com/pmmp/PocketMine-MP/commits/legacy/alpha11

**Comment by inxomnyaa** [comment]
I do not code plugins / PHP anymore.
