### ISSUE TITLE
please read

### ISSUE THREAD

**Issue by brexmania123** [inxomnyaa/MagicWE#49]
Hi so i saw your responce to my issue and i just wanted to say thats stupid... If you dont want to update it then send it to someone who can update it so it can work for the latest version of pmmp. This used to be the best world edit around, but how can it now since its outdated and will not even load. if you wanna be a dosh and not listen to the fans of this plugin then fine. all i was asking for was for you to update MagicWE2 to 3.0.0-ALPHA11. Is there really a huge problem with that? Usually i am polite when asking for things but the tags you added shows that you are not a nice person at all, so why should i show respect? there isnt a reason. So again if you dont want to update this then send it to someone who will update it and still give you credit!!!!!!

**Comment by inxomnyaa** [comment]
>  Is there really a huge problem with that? 

I have no money, can not pay my server, can not access my IDE (PHPStorm), have shitty internet (0.4mbit/s), and can not test the code.
People who want to update it can simply fork it and/or do a pull request.
