### ISSUE TITLE
Multiworld Support

### ISSUE THREAD

**Issue by ZandercraftGames** [inxomnyaa/MagicWE#57]
If you use the MagicWE2 plugin in one world, and then travel to another world using multiworld, warps, or EssentialsPE, and then try to use MagicWE2 in that world, it makes the change in the previous world. Found this out making changes to my hub and having absolutely destroy my plot-world.

**Comment by Aericio** [comment]
Confirmed. I've had some other people report this before.

It may be a while until this is fixed, however, because I am no "developer." I'll see if @thebigsmileXD has any motive to fix this, even though he lost all interest in the PM-API.

**Comment by ZandercraftGames** [comment]
Anything @Aericio ? @thebigsmileXD Please fix this...

**Comment by inxomnyaa** [comment]
This was fixed ages ago and can only be a PM issue. It seems that the Level object is not properly updated whilest teleporting to another world (@dktapps)

**Comment by ZandercraftGames** [comment]
@thebigsmileXD All other world edit plugins like worldstyler work 100% without fail and do not do this. But, your plugin is the best... So... I want to use it. But with this issue... I nearly broke my whole plotworld.

**Comment by inxomnyaa** [comment]
Cannot reproduce
