### ISSUE TITLE
[ Issue Beta-Update to 4.*] Undefined class constant 'RIGHT_CLICK_AIR

### ISSUE THREAD

**Issue by teracube** [inxomnyaa/MagicWE#60]
PocketMine-MP version 4.0.0+dev.1529
MagicWE2 v5.7.3 Dev # 106 Beta-Update to 4.* developer version

see attached error on server log

[issue api 4.0.0.log.zip](https://github.com/thebigsmileXD/MagicWE2/files/2455809/issue.api.4.0.0.log.zip)

**Comment by inxomnyaa** [comment]
Todo:change to RELEASE_ITEM_ACTION_RELEASE or better USE_ITEM_ACTION_CLICK_AIR
