### ISSUE TITLE
Translations!

### ISSUE THREAD

**Issue by inxomnyaa** [inxomnyaa/MagicWE#64]
### If you want to add a language (after Hacktoberfest), please create a pull request and reference this issue.

I want to introduce translations! Interested in "Hacktoberfest"? Here you can get started!

Any language is appreciated <3

Readme may not be translated (too difficult to keep it updated)

A template translation:
https://github.com/thebigsmileXD/MagicWE2/blob/master/resources/eng.ini

The translation files must be in a 3-letter format like here: https://iso639-3.sil.org/code_tables/macrolanguage_mappings/data

**Comment by karate** [comment]
Would you be interested in Greek?

**Comment by fuku710** [comment]
I will translate to Japanese!

**Comment by rodrigobustamante** [comment]
I will translate to Spanish dude!

**Comment by GledsonAfonso** [comment]
I will translate to Brazilian Portuguese.

**Comment by rapirent** [comment]
I will translate to Traditional Chinese!

**Comment by LuisPaGarcia** [comment]
I just added spanish translation and README in spanish.

#69

**Comment by LuisPaGarcia** [comment]
I just added spanish translation and README in spanish.

PR #69

**Comment by inxomnyaa** [comment]
Thanks everyone so far! I forgot to mention 1 thing:
the translation files must be in a 3-letter format like here: https://iso639-3.sil.org/code_tables/macrolanguage_mappings/data

Could everyone who contributed check their filenames if they are in the `xyz.ini` format? Thank you!

**Comment by JeromerT** [comment]
Added a Dutch translation

**Comment by JoaquinMontesinos** [comment]
Added a French translation

**Comment by JoaquinMontesinos** [comment]
Added a Italian translation

**Comment by JoaquinMontesinos** [comment]
Added a Catalan translation

**Comment by JoaquinMontesinos** [comment]
Added a Portuguese translation

**Comment by JoaquinMontesinos** [comment]
Added a Romanian translation

**Comment by JoaquinMontesinos** [comment]
Added a Slovak translation

**Comment by JoaquinMontesinos** [comment]
Added  a Polish translation

**Comment by Johnmacrocraft** [comment]
I might translate it into Korean because I'm bored now lol

**Comment by inxomnyaa** [comment]
A small notice to the "Flood" menu:

The "Flood" menu is meant to be like the Paint.exe Paint Bucket tool, maybe you can find a more fitting translation for it in your language :)

Thanks everyone for their commisions so far!

**Comment by GEveloper** [comment]
I will translate to Georgian!

**Comment by GEveloper** [comment]
> 
> 
> I will translate to Georgian!

#104

**Comment by GEveloper** [comment]
#104

**Comment by inxomnyaa** [comment]
Thanks for everyone who contributed!

I hope you had a great Hacktoberfest and you all got your T-Shirts ;)
