### ISSUE TITLE
Add permissions

### ISSUE THREAD

**Issue by OfficialLilKev** [inxomnyaa/MagicWE#7]
Add all permissions for commands any player can use the commands

**Comment by inxomnyaa** [comment]
@isozy told me today already, the session branch has a temp fix

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MagicWE2/commit/00141b92df49868a2a24e4d501360e479187ec90

**Comment by inxomnyaa** [comment]
That actually is the schematics branch 🌚😂

**Comment by OfficialLilKev** [comment]
So you gonna add permissions

**Comment by inxomnyaa** [comment]
there are

**Comment by inxomnyaa** [comment]
Fixed in sessions and permission-fixes branches
